version: "3.9"
services:
  redis:
    ports:
      - "6379:6379"
    image: "redis:alpine"
  grabbers:
    build: .
    environment:
      REDIS_HOST: "redis"
    depends_on:
      - redis
    scale: 32

